=== tommaso1974/Osm2GpsMid/Osm2GpsMid/style-file.dtd
<!ELEMENT legend (version, colors, pois, ways, damages?, tileScaleLevels?, routeModes*, maxSpeedTemplates?)>
<!ELEMENT version EMPTY>
<!ELEMENT colors (color*)>
<!ELEMENT color EMPTY>
<!ELEMENT pois (key*)>
<!ELEMENT ways (keyW*)>
<!ELEMENT damages (damage*)>
<!ELEMENT routeModes (routeMode*)>
<!ELEMENT routeMode (routeAccessRestriction*, tollRule*)>
<!ELEMENT maxSpeedTemplates (maxSpeedTemplate*)>
<!ELEMENT tileScaleLevels (tileScaleLevel*)>
<!ELEMENT key (value+)>
<!ELEMENT keyW (Wvalue+)>
<!ELEMENT value (specialisation*, description , image? , searchIcon? , namekey , namefallback? , housenumberindex?, helpertag? , AreaPOI?, scale , textscale? , imageCentered?, hideable?, alert?, clickable?)>
<!ELEMENT Wvalue (specialisation*, description, asRelation?, image? , searchIcon? , namekey, namefallback?, housenumberindex?, helpertag?, showName?, isArea, ignoreOsmAreaTag?, scale, textscale?, arrowscale?, descriptionscale?, lineColor, borderColor?, lineStyle?, wayWidth?, searchIcon?, routing*, force_to?, hideable?, alert?, clickable?)>
<!ELEMENT damage EMPTY>
<!ELEMENT routeAccessRestriction EMPTY>
<!ELEMENT restrictionKey EMPTY>
<!ELEMENT restrictionValues EMPTY>
<!ELEMENT tollRule EMPTY>
<!ELEMENT description EMPTY>
<!ELEMENT image EMPTY>
<!ELEMENT asRelation EMPTY>
<!ELEMENT searchIcon EMPTY>
<!ELEMENT namekey EMPTY>
<!ELEMENT namefallback EMPTY>
<!ELEMENT helpertag EMPTY>
<!ELEMENT housenumberindex EMPTY>
<!ELEMENT scale EMPTY>
<!ELEMENT textscale EMPTY>
<!ELEMENT arrowscale EMPTY>
<!ELEMENT descriptionscale EMPTY>
<!ELEMENT imageCentered EMPTY>
<!ELEMENT showName EMPTY>
<!ELEMENT isArea EMPTY>
<!ELEMENT ignoreOsmAreaTag EMPTY>
<!ELEMENT lineColor EMPTY>
<!ELEMENT borderColor EMPTY>
<!ELEMENT lineStyle EMPTY>
<!ELEMENT wayWidth EMPTY>
<!ELEMENT routing EMPTY>
<!ELEMENT force_to EMPTY>
<!ELEMENT hideable EMPTY>
<!ELEMENT AreaPOI EMPTY>
<!ELEMENT specialisation EMPTY>
<!ELEMENT maxSpeedTemplate EMPTY>
<!ELEMENT tileScaleLevel EMPTY>
<!ELEMENT alert EMPTY>
<!ELEMENT clickable EMPTY>
<!ATTLIST version release CDATA #REQUIRED>
<!ATTLIST key tag CDATA #REQUIRED>
<!ATTLIST keyW tag CDATA #REQUIRED>
<!ATTLIST value name CDATA #REQUIRED>
<!ATTLIST value priority CDATA #IMPLIED>
<!ATTLIST Wvalue name CDATA #REQUIRED>
<!ATTLIST Wvalue priority CDATA #IMPLIED>
<!ATTLIST style is CDATA #REQUIRED>
<!ATTLIST ignore is CDATA #REQUIRED>
<!ATTLIST color of CDATA #REQUIRED>
<!ATTLIST color is CDATA #REQUIRED>
<!ATTLIST color isAtNight CDATA #IMPLIED>
<!ATTLIST routeAccessRestrictions for CDATA #REQUIRED>
<!ATTLIST description desc CDATA #REQUIRED>
<!ATTLIST namekey tag CDATA #REQUIRED>
<!ATTLIST namefallback tag CDATA #REQUIRED>
<!ATTLIST helpertag tag CDATA #REQUIRED>
<!ATTLIST housenumberindex index CDATA #REQUIRED>
<!ATTLIST housenumberindex matchtag CDATA #IMPLIED>
<!ATTLIST scale scale CDATA #REQUIRED>
<!ATTLIST textscale scale CDATA #REQUIRED>
<!ATTLIST arrowscale scale CDATA #REQUIRED>
<!ATTLIST descriptionscale scale CDATA #REQUIRED>
<!ATTLIST image src CDATA #REQUIRED>
<!ATTLIST asRelation relation CDATA #REQUIRED>
<!ATTLIST asRelation combined CDATA #IMPLIED>
<!ATTLIST searchIcon src CDATA #REQUIRED>
<!ATTLIST imageCentered value CDATA #REQUIRED>
<!ATTLIST showName style CDATA #REQUIRED>
<!ATTLIST isArea area CDATA #REQUIRED>
<!ATTLIST ignoreOsmAreaTag ignore CDATA #REQUIRED>
<!ATTLIST lineColor color CDATA #REQUIRED>
<!ATTLIST lineColor colorAtNight CDATA #IMPLIED>
<!ATTLIST borderColor color CDATA #REQUIRED>
<!ATTLIST borderColor colorAtNight CDATA #IMPLIED>
<!ATTLIST lineStyle dashed CDATA #REQUIRED>
<!ATTLIST wayWidth width CDATA #REQUIRED>
<!ATTLIST routing with CDATA #REQUIRED>
<!ATTLIST routing accessible CDATA #REQUIRED>
<!ATTLIST routing speed CDATA #REQUIRED>
<!ATTLIST force_to layer CDATA #REQUIRED>
<!ATTLIST hideable hideable CDATA #REQUIRED>
<!ATTLIST alert alert CDATA #REQUIRED>
<!ATTLIST clickable clickable CDATA #REQUIRED>
<!ATTLIST AreaPOI createForAreas CDATA #REQUIRED>
<!ATTLIST specialisation condition CDATA "match">
<!ATTLIST specialisation key CDATA #REQUIRED>
<!ATTLIST specialisation value CDATA #REQUIRED>
<!ATTLIST specialisation regexp CDATA #IMPLIED>
<!ATTLIST specialisation properties CDATA #IMPLIED>
<!ATTLIST routeMode modeName CDATA #REQUIRED>
<!ATTLIST routeMode maxPrepareMeters CDATA #REQUIRED>
<!ATTLIST routeMode maxInMeters CDATA #REQUIRED>
<!ATTLIST routeMode maxEstimationSpeed CDATA #REQUIRED>
<!ATTLIST routeMode applyTurnRestrictions CDATA #IMPLIED>
<!ATTLIST routeMode againstAllOneWays CDATA #IMPLIED>
<!ATTLIST routeMode bicycleOppositeExceptions CDATA #IMPLIED>
<!ATTLIST routeMode mainStreetNet CDATA #IMPLIED>
<!ATTLIST routeAccessRestriction restrictionKey CDATA #REQUIRED>
<!ATTLIST routeAccessRestriction restrictionValues CDATA #REQUIRED>
<!ATTLIST routeAccessRestriction restrictionPermit CDATA #IMPLIED>
<!ATTLIST tollRule tollKey CDATA #REQUIRED>
<!ATTLIST tollRule tollValues CDATA #REQUIRED>
<!ATTLIST tollRule enableToll CDATA #REQUIRED>
<!ATTLIST tollRule debugTollRule CDATA #IMPLIED>
<!ATTLIST damage damageKey CDATA #REQUIRED>
<!ATTLIST damage damageValues CDATA #REQUIRED>
<!ATTLIST maxSpeedTemplate name CDATA #REQUIRED>
<!ATTLIST maxSpeedTemplate maxspeed CDATA #REQUIRED>
<!ATTLIST tileScaleLevel level CDATA #REQUIRED>
<!ATTLIST tileScaleLevel minScale CDATA #REQUIRED>
<!ATTLIST tileScaleLevel allowedForRoutableWays CDATA #IMPLIED>
<!ATTLIST tileScaleLevel attractAreasWithSmallerBoundsDiameterThan CDATA #IMPLIED>

=== tommaso1974/Osm2GpsMid/Osm2GpsMid/mini-style-file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE legend SYSTEM "style-file.dtd" [
<!ENTITY maxspeed SYSTEM "maxspeed_templates.inc">
<!ENTITY colors SYSTEM "colors.inc">
<!ENTITY routemodes SYSTEM "routemodes.inc">
<!ENTITY tilescale SYSTEM "tilescale.inc">
<!ENTITY damages SYSTEM "damages.inc">
]>
<!--
This is the so-called mini style file for Osm2GpsMid.
It evolved from the original default style so many things are different than in
style-file.xml. Most zoom level limits for displaying different features are different.
It is questionable whether these differences provide a big enough benefit (i.e.
less memory usage, faster map display, nicer map) compared to the extra effort 
needed to maintain this style.
It should be discussed whether both reduced-style-file.xml and this style should
be maintained.

In general, style files allow to specify which map features get converted from 
the OSM data to GpsMid. This can and should be changed at will to suit
your personal preferences, as long as it conforms to style-file.dtd.

WARNING: There is currently one extra restriction. The "key tag=place"
currently must be the first in the stylefile and must contain 5 different
places in decending order or importance. This is due to some hardcoded
assumptions in the code for calculating is_in relations for the search
dialog.
-->

<!-- available aliases for the scale parameter:
scale alias 31: zoomed in 9x
scale alias 30: zoomed in 8x
scale alias 29: zoomed in 7x
scale alias 28: zoomed in 6x
scale alias 27: zoomed in 5x
scale alias 26: zoomed in 4x
scale alias 25: zoomed in 3x
scale alias 24: zoomed in 2x
scale alias 23: zoomed in 1x
scale alias 22: startup zoom level of GpsMid
scale alias 21: zoomed out 1x
scale alias 20: zoomed out 2x
scale alias 19: zoomed out 3x
scale alias 18: zoomed out 4x
scale alias 17: zoomed out 5x
scale alias 16: zoomed out 6x
scale alias 15: zoomed out 7x
scale alias 14: zoomed out 8x
scale alias 13: zoomed out 9x
scale alias 12: zoomed out 10x
scale alias 11: zoomed out 11x
scale alias 10: zoomed out 12x
scale alias 9: zoomed out 13x
scale alias 8: zoomed out 14x
scale alias 7: zoomed out 15x
scale alias 6: zoomed out 16x
scale alias 5: zoomed out 17x
scale alias 4: zoomed out 18x
scale alias 3: zoomed out 19x
scale alias 2: zoomed out 20x
scale alias 1: zoomed out 21x
-->

<legend>
  <version release="0.6.0"/>
  
     &colors;
        
<!-- SoundFiles for these sounds are automatically included into the midlet unless useRouting=false is set in .properties file:
	 CONNECT, DISCONNECT, PREPARE, HALF, HARD, BEAR, LEFT, RIGHT, UTURN, THEN, SOON, AGAIN, TO, ENTER_MOTORWAY, LEAVE_MOTORWAY,
	 RAB, 1ST, 2ND, 3RD, 4TH, 5TH, 6TH, RABEXIT, CHECK_DIRECTION, ROUTE_RECALCULATION, DEST_REACHED,
	 IN, 100, 200, 300, 400, 500, 600, 700, 800, METERS, INTO_TUNNEL, OUT_OF_TUNNEL, FOLLOW_STREET,
	 AREA_CROSS, AREA_CROSSED, SPEED_LIMIT
	 Set in your properties file with which extension these sound files are included (lowercase name + .extension)
	 e.g. useSounds=wav, amr will include e.g. prepare.wav and prepare.amr, etc.
	 You can also provide external versions of those files
	 in a sound sub-directory of the Osm2GpsMid directory (when using internal style-file)
	 or in the directory or a sound sub-directory of the style-file.
-->
  
<!-- POIs to be included
	 If there is no internal version in Osm2GpsMid for the png files, you must provide external versions
	 in the directory or a sound sub-directory of the Osm2GpsMid directory (when using internal style-file)
	 or in the directory or a sound sub-directory of the style-file.
-->	
  <pois>
	<key tag="place">
	   <value name="city">
		<description desc = "City"/>
		<searchIcon src = "city.png"/>
		<namekey tag="name"/>		
		<scale scale="12"/>
		<hideable hideable="false"/>
	  </value>
	  <value name="town">
		<description desc = "Town"/>
		<searchIcon src = "city.png"/>
		<namekey tag="name"/>
		<scale scale = "16"/>
		<hideable hideable="false"/>
	  </value>
	  <value name="village">
		<description desc = "Village"/>
		<searchIcon src = "city.png"/>
		<namekey tag="name"/>
		<scale scale = "22"/>
		<hideable hideable="false"/>
	  </value>
	  <value name="hamlet">
		<description desc = "Hamlet"/>
		<searchIcon src = "city.png"/>
		<namekey tag="name"/>
		<scale scale = "23"/>
		<hideable hideable="false"/>
	  </value>
	  <value name="suburb">
		<description desc = "Suburb"/>
		<searchIcon src = "city.png"/>
		<namekey tag="name"/>
		<scale scale = "23"/>
		<hideable hideable="false"/>
	  </value>
	</key>
	<key tag="amenity">
	  <value name ="post_box">
		<description desc = "Post box"/>
		<image src="post_box.png"/>
		<namekey tag="name"/>
		<scale scale="25"/>
		<textscale scale="18"/>
	  </value>	
	  <value name ="post_office">
		<description desc = "Post office"/>
		<image src="post_office.png"/>
		<namekey tag="name"/>
		<scale scale="23"/>
		<textscale scale="18"/>
	  </value>	
	  <value name ="school">
		<description desc = "School"/>
		<image src="school.png"/>
		<namekey tag="name"/>
		<scale scale="24"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="telephone">
		<description desc = "Public telephone"/>
		<image src="telephone.png"/>
		<namekey tag="name"/>
		<scale scale="25"/>
		<textscale scale = "26"/>
	  </value>
	  <value name ="emergency_phone">
		<description desc = "Emergency phone"/>
		<image src="emergency_phone.png"/>
		<namekey tag="name"/>
		<scale scale="20"/>
		<textscale scale="23"/>
	  </value>
	  <value name ="restaurant">
		<description desc = "Restaurant"/>
		<image src="restaurant.png"/>
		<namekey tag="name"/>
		<scale scale="24"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="hospital">
		<description desc = "Hospital"/>
		<image src="hospital.png"/>
		<namekey tag="name"/>
		<scale scale="20"/>
		<textscale scale="24"/>
	  </value>
	  <value name ="pub">
		<description desc = "Pub"/>
		<image src="pub.png"/>
		<namekey tag="name"/>
		<scale scale="25"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="atm">
		<description desc = "Cash machine"/>
		<image src="atm.png"/>
		<namekey tag="operator"/>
		<namefallback tag="name"/>
		<scale scale="25"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="cinema">
		<description desc = "Cinema"/>
		<image src="cinema.png"/>
		<namekey tag="name"/>
		<scale scale="24"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="pharmacy">
		<description desc = "Pharmacy"/>
		<image src="pharmacy.png"/>
		<namekey tag="name"/>
		<scale scale="24"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="place_of_worship" priority="10">
		<specialisation key="religion" value="christian"/>
		<description desc = "Church"/>
		<image src="church.png"/>
		<namekey tag="name"/>
		<scale scale="23"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="place_of_worship" priority="10">
		<specialisation key="religion" value="jewish"/>
		<description desc = "Synagogue"/>
		<image src="jewish.png"/>
		<namekey tag="name"/>
		<scale scale="23"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="place_of_worship" priority="10">
		<specialisation key="religion" value="muslim"/>
		<description desc = "Mosque"/>
		<image src="muslim.png"/>
		<namekey tag="name"/>
		<scale scale="23"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="place_of_worship" priority="5">
		<description desc = "Place of worship"/>
		<image src="religion.png"/>
		<namekey tag="name"/>
		<scale scale="23"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="fuel">
		<description desc = "Fuel station"/>
		<image src="fuel.png"/>
		<namekey tag="operator"/>
		<namefallback tag="name"/>
		<scale scale="23"/>
		<textscale scale="26"/>		
	  </value>
	  <value name ="bicycle_parking">
		<description desc = "Bicycle parking"/>
		<image src="bicycle_parking.png"/>
		<namekey tag="name"/>
		<scale scale="23"/>
		<textscale scale="26"/>		
	  </value>
	  <value name ="toilets">
		<description desc = "Public toilet"/>
		<image src="toilets.png"/>
		<namekey tag="name"/>
		<scale scale="25"/>
		<textscale scale="26"/>		
	  </value>
	  <value name ="recycling">
		<description desc = "Recycling"/>
		<image src="recycling.png"/>
		<namekey tag="name"/>
		<scale scale="25"/>
		<textscale scale="26"/>		
	  </value>
	  <value name ="library">
		<description desc = "Library"/>
		<image src="library.png"/>
		<namekey tag="name"/>
		<scale scale="22"/>
		<textscale scale="26"/>		
	  </value>
	  <value name ="biergarten">
		<description desc = "Biergarten"/>
		<image src="biergarten.png"/>
		<namekey tag="name"/>
		<scale scale="25"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="fire_station">
		<description desc = "Fire station"/>
		<image src="firebrigade.png"/>
		<namekey tag="name"/>
		<scale scale="25"/>
		<textscale scale="26"/>
	  </value>	
	  <value name ="police">
		<description desc = "Police station"/>
		<image src="police.png"/>
		<namekey tag="name"/>
		<scale scale="24"/>
		<textscale scale="26"/>
	  </value>	
	  <value name ="parking">
		<description desc = "Car parking"/>
		<image src="parking.png"/>
		<namekey tag="name"/>
		<scale scale="23"/>
		<textscale scale="26"/>
	  </value>
	  <value name ="taxi">
		<description desc = "Taxi"/>
		<image src="taxi.png"/>
		<namekey tag="name"/>
		<scale scale="23"/>
		<textscale scale="26"/>
	  </value>
	</key>
	<key tag="shop">
	   <value name="supermarket">
		<description desc = "Supermarket"/>
		<image src="supermarket.png"/>
		<namekey tag="name"/>
		<scale scale="22"/>
		<textscale scale="26"/>
	  </value>
	  <value name="kiosk">
		<description desc = "Kiosk"/>
		<image src="kiosk.png"/>
		<namekey tag="name"/>
		<scale scale="25"/>
		<textscale scale="26"/>
	  </value>
	</key>
	<key tag="highway">
	  <value name="bus_stop">
		<description desc = "Bus stop"/>
		<image src="bus.png"/>		
		<namekey tag="name"/>
		<scale scale="22"/>
		<textscale scale="26"/>
		<imageCentered value="true"/>
	  </value>
	  <value name="motorway_junction">
